# Dossiers que l'on va utiliser

'FASTA': "DATA/ref/riceNUCMSU7.fasta"
'GFF': "DATA/annotation/riceNUCMSU7.gff"
'GTF': "DATA/annotation/riceNUCMSU7.gtf"
'READS': "DATA/fastq/"
'OUTDIR': "output"

### logiciels
'FastQScreen_conf': "ConfigFastqScreen.txt"
'name_hisat_index': "rice"