###################
# Input output data options
'DATA':
    'directories':
        'out_dir': "output2"       # Out directory
    'files':
        'reference': "DATA/ref/allcon.fasta"
        'annotation': "DATA/ref/msu7.gtf"
        'sample_info': "DATA/sample_info.txt"
        'de_comparisons_file': "DATA/treatmentsComparisons.csv"
'DE':
# filtering
    'cutoff_cpm': 5
    'cutoff_nb_echantillons': 2
# threshold DE
    'thres_FDR': 0.01
    'thres_logFC': 1.5

SINGULARITY:
    "MAIN": "RNAja/envs/Singularity.RNAja.sif"
