###################
# Input output data options
'DATA':
    'directories':
        'out_dir': "output2"       # Out directory
    'files':
        'reference': "DATA/ref/allcon.fasta"
        'annotation': "DATA/ref/msu7.gtf"
        'sample_info': "DATA/sample_info.txt"
        'de_comparisons_file': "DATA/treatmentsComparisons.csv"

##############################
# Location of various software

SINGULARITY:
    "MAIN": "RNAja/envs/Singularity.RNAja.sif"
