# Dossiers que l'on va utiliser

'REFERENCE': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/01_Genome/"
'FASTA': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/01_Genome/plasmodb_pfalciparum3d7_genome.fasta"
'GFF': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/01_Genome/plasmodb-46_pfalciparum3d7.gff"
'GTF': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/01_Genome/plasmodb-46_pfalciparum3d7.gtf"
'READS': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/02_RawData/"
'FASTQC': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/03_FastQC/"
'FASTQSCREEN': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/04_FastQScreen/"
'FASTP': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/05_FastP/"
'FASTQC_AF': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/06_FastQC_AfterFT/"
'MULTIQC': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/07_MultiQC/"
'INDEX': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/08_Index_HISAT_3D7/"
'MAPPINGH': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/09_Mapping_HISAT_3D7/"
'INDEX_STAR': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/10_Index_STAR_3D7/"
'MAPPING_STAR': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/11_Mapping_STAR_3D7/"
'BAMFILES': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/12_BAMfiles/"
'STATS': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/14_Stats_BAM/"
'FILTER': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/13_Filtered_BAM/"
'DUPL': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/15_MarkedDupli_BAM/"
'HTSEQ': "/Users/COHEN/Documents/BulKRNA/TestSnakeMake/16_HTseq-count/"

###Options des logiciels
